docs update for rule yaml naming changes
amalgam8/amalgam8.github.io pull request #109
Opened 2017-03-07 19:13 UTC by GregHanson

2017-03-07 19:28 UTC, ijsnellf requested changes

2017-03-07 19:28 UTC, ijsnellf commented on _docs/4-kubernetes/1-controlplane.md
> +Amalgam8 runs a control-loop to validate routing rules stored in Third Party Resources (TPR)
This is inaccurate. The controller validates incoming rules before storing them as TPRs.

2017-03-07 19:28 UTC, ijsnellf commented on _docs/4-kubernetes/2-helloworld.md
> +    NAME                             KIND
`a8ctl rule-get -a -o json`

2017-03-07 19:28 UTC, ijsnellf commented on _docs/4-kubernetes/3-bookinfo.md
> +   $ kubectl get routingrule bookinfo-jason-reviews-v2-route-rules -o json
`a8ctl rule-get -i bookinfo-jason-reviews-v2-route-rules -o json`

2017-03-07 19:38 UTC, GregHanson commented on _docs/4-kubernetes/2-helloworld.md
> +    NAME                             KIND
@rshriram @elevran do we just want to get rid of the entire `4-kubernetes` section?  Assuming the docs in `1-demo` cover everything kubernetes related?

2017-03-07 23:08 UTC, rshriram commented on _docs/4-kubernetes/2-helloworld.md
> +    NAME                             KIND
Yes..

2017-03-08 01:55 UTC, rshriram commented on _docs/4-kubernetes/2-helloworld.md
> +    NAME                             KIND
Well, make sure that there all info in the k8s section is covered in demo. Secondly, I would take the description on TPR stuff and stick it into the controller page as an implementation note

2017-03-08 21:12 UTC, ijsnellf approved these changes

2017-03-08 21:40 UTC, rshriram approved these changes

2017-03-08 21:40 UTC, rshriram commented on _docs/2-controlplane/1-controller/configuration-options.md
> +          value: kubernetes
k8s or kubernetes?

2017-03-09 14:17 UTC, GregHanson commented on _docs/2-controlplane/1-controller/configuration-options.md
> +          value: kubernetes
according etai, our naming convention has been `kubernetes` for similar environment variables

2017-03-09 14:18 UTC, merged